# Generated by Django 3.1.7 on 2021-02-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
