# Generated by Django 3.1.7 on 2021-02-26 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210226_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
