# Generated by Django 3.1.7 on 2021-02-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210226_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='transactionType',
            field=models.CharField(default='Undefined', max_length=100),
        ),
    ]
