# Generated by Django 3.1.7 on 2021-02-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210226_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='receiverAccountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverAccount', to='api.account'),
        ),
    ]
